### ISSUE TITLE
pymongo: TypeError: count() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by thorgrin** [CESNET/liberouter-gui#10]
I've just came across the following bug (/var/log/httpd/ssl_error_log):
```
[Mon Aug 07 12:56:11.842596 2017] [wsgi:error] [pid 3456] [remote 10.0.2.15:45168] mod_wsgi (pid=3456): Target WSGI script '/var/www/html/liberouter-gui/api/wsgi.py' cannot be loaded as Python module.
[Mon Aug 07 12:56:11.842624 2017] [wsgi:error] [pid 3456] [remote 10.0.2.15:45168] mod_wsgi (pid=3456): Exception occurred processing WSGI script '/var/www/html/liberouter-gui/api/wsgi.py'.
[Mon Aug 07 12:56:11.842646 2017] [wsgi:error] [pid 3456] [remote 10.0.2.15:45168] Traceback (most recent call last):
[Mon Aug 07 12:56:11.842686 2017] [wsgi:error] [pid 3456] [remote 10.0.2.15:45168]   File "/var/www/html/liberouter-gui/api/wsgi.py", line 12, in <module>
[Mon Aug 07 12:56:11.842689 2017] [wsgi:error] [pid 3456] [remote 10.0.2.15:45168]     from liberouterapi import app as application
[Mon Aug 07 12:56:11.842707 2017] [wsgi:error] [pid 3456] [remote 10.0.2.15:45168]   File "/var/www/html/liberouter-gui/api/liberouterapi/__init__.py", line 59, in <module>
[Mon Aug 07 12:56:11.842710 2017] [wsgi:error] [pid 3456] [remote 10.0.2.15:45168]     check_users()
[Mon Aug 07 12:56:11.842725 2017] [wsgi:error] [pid 3456] [remote 10.0.2.15:45168]   File "/var/www/html/liberouter-gui/api/liberouterapi/bootstrap.py", line 73, in check_users
[Mon Aug 07 12:56:11.842728 2017] [wsgi:error] [pid 3456] [remote 10.0.2.15:45168]     if db.users.count() == 0:
[Mon Aug 07 12:56:11.842742 2017] [wsgi:error] [pid 3456] [remote 10.0.2.15:45168] TypeError: count() takes at least 1 argument (0 given)
```

I've installed clean STaaS Vagrant box, liberouter gui uses release v0.3.2 and git is at commit a53814a. It happened several times before but I have no idea what caused it. The error went away after restarting mongod and apache services. Is it possible that there is some kind of error with connection to the mongo database right after installation?

**Comment by petrstehlik** [comment]
It takes mongod process to start up correctly a couple of seconds (especially on small machines). During this time the database connector can act nondeterministically. There should be a check if the connector is initialized properly.

**Comment by thorgrin** [comment]
I've noticed that it is often not enough to wait or restart mongo. The Apache needs to be restarted as well, which is weird.

**Comment by petrstehlik** [comment]
It might be caused by mod_wsgi itself. Occasionally it can hang on requests when an exception in the flask app is raised. I'd suggest trying to proxy the app via Apache and run the app using uwsgi or similar service to see if it's Apache/mod_wsgi problem or not.

The command for uwsgi should be like this: `uwsgi --http :5555 --gevent 1000 --wsgi-file wsgi.py`

First you need the uwsgi and gevent modules installed (both are available via pip) and run it from `api/` folder. Then configure proxypass for Apache as is shown in the [README.md](https://github.com/CESNET/liberouter-gui/blob/master/api/README.md) in `api/` folder.

**Comment by petrstehlik** [comment]
Closing for inactivity.
