### ISSUE TITLE
bootstrap: key error when devDependencies are not specified

### ISSUE THREAD

**Issue by petrstehlik** [CESNET/liberouter-gui#35]
When a package.json is present in a module which has only dependencies (no devDependencies) the bootstrap.py script fails on KeyError:
```python
Traceback (most recent call last):
  File "bootstrap.py", line 263, in <module>
    bootstrapModules(depsBase, moduleList)
  File "bootstrap.py", line 198, in bootstrapModules
    updateDeps(basedeps, config['dependencies'], module)
  File "bootstrap.py", line 129, in updateDeps
    mergeNpmDeps(basedeps[Deps.NPM], npmd, modulename)
  File "bootstrap.py", line 57, in mergeNpmDeps
    conflicts = Unify.dicts(base[item], module[item])
KeyError: 'devDependencies'
```

**Comment by alexpnt** [comment]
I submitted a PR for this issue

**Comment by petrstehlik** [comment]
Thank you for your PR. I just merged to devel and the fix will be available in next release.

Happy Hacktoberfest!
