### ISSUE TITLE
Unmet dependency on reporter_config

### ISSUE THREAD

**Issue by thorgrin** [CESNET/liberouter-gui#7]
i'm getting the following error after upgrading from v0.3.1 to v0.3.2:
```
[Fri Aug 04 12:09:45.676086 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569] mod_wsgi (pid=3383): Target WSGI script '/var/www/html/liberouter-gui/api/wsgi.py' cannot be loaded as Python module.
[Fri Aug 04 12:09:45.676132 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569] mod_wsgi (pid=3383): Exception occurred processing WSGI script '/var/www/html/liberouter-gui/api/wsgi.py'.
[Fri Aug 04 12:09:45.676163 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569] Traceback (most recent call last):
[Fri Aug 04 12:09:45.676217 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569]   File "/var/www/html/liberouter-gui/api/wsgi.py", line 12, in <module>
[Fri Aug 04 12:09:45.676221 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569]     from liberouterapi import app as application
[Fri Aug 04 12:09:45.676257 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569]   File "/var/www/html/liberouter-gui/api/liberouterapi/__init__.py", line 77, in <module>
[Fri Aug 04 12:09:45.676261 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569]     import_modules()
[Fri Aug 04 12:09:45.676282 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569]   File "/var/www/html/liberouter-gui/api/liberouterapi/bootstrap.py", line 37, in import_modules
[Fri Aug 04 12:09:45.676286 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569]     fromlist=[mod_name])
[Fri Aug 04 12:09:45.676309 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569]   File "/var/www/html/liberouter-gui/api/liberouterapi/modules/nemea/__init__.py", line 16, in <module>
[Fri Aug 04 12:09:45.676313 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569]     from .Reporters import *
[Fri Aug 04 12:09:45.676346 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569]   File "/var/www/html/liberouter-gui/api/liberouterapi/modules/nemea/Reporters.py", line 12, in <module>
[Fri Aug 04 12:09:45.676351 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569]     from reporter_config.Parser import Parser
[Fri Aug 04 12:09:45.676372 2017] [wsgi:error] [pid 3383] [remote 10.0.2.2:42569] ImportError: No module named 'reporter_config'
```

Unfortunately, the package python34-nemea-pycommon containing the module has unmet dependencies and cannot be easily installed. Can reporter_config be removed from dependencies or installed in any other way?

**Comment by petrstehlik** [comment]
Fixed CESNET/Nemea-Dashboard@696126b3d26001235644f052b4771b788e03896a
